= 연습 2: Docker 이미지 빌드

Docker가 사전 설치된 Cloud Shell을 개발 환경으로 사용하고 있습니다. 여기에서는 Docker 이미지를 빌드합니다.

아래 절차에 따릅니다.

1. Cloud Shell에서 아래 명령을 실행하여 Cloud Shell에 설치된 Docker 버전을 확인합니다.
+
----
$ docker -v
----
+
결과는 아래와 같이 표시됩니다.
+
----
podman version 4.9.4-rhel
----
+
NOTE: Oracle Cloud Shell의 docker 명령은 Podman(podman 버전 4.9.4-rhel)에 매핑됩니다. 일부 Docker 명령, 특히 권한 있는 포트(1024 미만)를 사용하는 명령은 조정이 필요할 수 있습니다(예: 80번 포트 대신 8080번 포트와 같은 일반 포트 사용).

2. Cloud Shell의 Docker 이미지를 확인합니다.
+
----
$ docker images
----

3. 아래 명령을 실행하여 현재 디렉토리가 `docker-helloworld-demo` 인것을 확인합니다.
+
----
$ pwd
----

4. `docker build` 명령을 사용하여 샘플 웹 애플리케이션 docker 이미지를 생성합니다. 이 명령은 파라미터를 필요로 합니다.
+
----
$ docker build -t oci_sample_webapp_<userID>:<tag> .
----
+
명령의 실행 예는 아래와 같습니다:
+
----
$ docker build -t oci_sample_webapp_user01:1.0 .
----
+
파라미터는 아래와 같습니다.

* `-t`: 이미지 이름을 지정하는 데 사용됩니다.
* `tag`: 이미지의 버전을 지정하는 데 사용됩니다. 이 연습에서는 1.0을 지정합니다.
* 현재 Dockerfile이 포함된 클론 디렉토리에 있습니다. 명령 끝에 상대 경로로 "."를 사용하십시오.

5. Docker 이미지 생성이 완료되면, 아래 명령을 실행하여 local 리포지토리에 빌드된 이미지를 확인합니다.
+
----
$ docker images
----
+
명령 실행 결과로 두개의 항목을 보게 됩니다. 하나는 `Nginx` 의 기본 이미지이며, 다른 하나는 웹 애플리케이션 `oci_sample_webapp_<userID>` 를 위한 사용자 정의 Docker 이미지입니다.

다음: link:./03_run_docker_image_as_container.adoc[Docker 이미지를 컨테이너로 실행]