= 연습 4: Kubernetes (OKE) Secret 생성

Kubernetes가 애플리케이션 배포 시 OCIR 저장소에서 이미지를 가져오도록 하려면 Kubernetes 시크릿을 생성해야 합니다. 시크릿에는 인증 토큰을 포함하여 `docker in` 명령어를 사용하여 OCIR에 로그인할 때 제공하는 세부 정보가 포함됩니다.

아래 절차를 따릅니다.

1. OCI 콘솔에서, 오른쪽 위의 **Developer Tools**를 클릭하고 **Cloud Shell**을 클릭하여 Cloud Shell을 실행합니다.
+
NOTE: 클라우드 셸에서 실행되는 OCI CLI는 클라우드 셸 시작 시 콘솔의 지역 선택 메뉴에서 선택한 지역을 대상으로 명령을 실행합니다.

2. 아래 명령을 실행하여 Secret을 생성합니다.
+
----
$ kubectl create secret docket—registry <name—of—secret>-<userID> --docker—server=<region-key>.ocir.io --docker-username='<tenancy-name>/ <oci—username> --docker—password='<oci—auth—token> --docker—email=' <email—address>' -n ns-<userlD> 
----
+
명령의 실행 예는 다음과 같습니다:
+
----
$ kubectl create secret docker-registry ocir-secret-user01 --docker-server=iad.ocir.io --docker-username='idw9qpcf8tyn/sanghoon.k.kim@oracle.com' --docker-password=')ZSKLXuh1T:6cq9n0C:C' --docker-email='sanghoon.k.kim@oracle.com' -n ns-user01
----
+
실행 결과는 아래와 같습니다
+
----
secret/ocir-secret-user01 created
----

* `<name-of-secret>-<userlD>`: 비밀번호에 사용할 고유한 이름입니다. 예를 들어, ocir-secret-user01입니다. <사용자 ID>를 사용자 ID로 변경합니다. 사용자 ID는 OCI 콘솔의 프로필 섹션에 표시되는 사용자 이름입니다.
* `<region-key>`: 사용 중인 Oracle Cloud Infrastructure 리전의 키입니다. 예를 들어, iad는 미국 동부(애쉬번) 리전의 리전 키입니다. 
* `ocir.io`: Oracle Cloud Infrastructure (OCI)의 레지스트리 이름입니다.
* `<tenancy-namespace>`: 는 이미지를 푸시할 테넌시(테넌시 정보 페이지에 표시됨)의 자동 생성된 객체 스토리지 네임스페이스 문자열입니다. 예를 들어 oracletenancy`입니다. 
* `<oci-auth-token>`: 이전 실습에서 IAD-AP-LAB09-1-AT-01에 대해 생성하여 메모장에 저장한 인증 토큰(임의 문자열)을 사용하십시오. 예를 들어, `R5kwpS-xxxxx((151rl)]`

3. 아래 명령을 실행하여 생성된 secret을 확인합니다.
+
----
$ kubectl get secrets -n ns-<userID>
----
+
결과는 아래와 같습니다.
+
----
NAME                 TYPE                             DATA   AGE
ocir-secret-user01   kubernetes.io/dockerconfigjson   1      110s
----

---

다음: link:./05_add_secret_imagepath.adoc[Deployment Manifest에 Secret과 이미지 경로 추가]